all:
	gcc -o pcap_A03_send_v5_fin pcap_A03_send_v5_fin.c -w -lpcap

clean:
	rm pcap_A03_send_v1
	rm pcap_A03_send_v2
	rm pcap_A03_send_v3
	rm pcap_A03_send_v4
	rm pcap_A03_send_v5_fin
	rm _pcap_func.o
	rm test_header.o
	rm test_header
	rm index.html* -rf
